### ISSUE TITLE
Entire plugin doesn't work, just installed it. Close please

### ISSUE THREAD

**Issue by AngelOfCreation** [egg82/TrollCommandsPlusPlus#3] opened 2017-08-28 22:38 UTC
I installed the plugin in my plugins folder and restarted the server several times, but  when I do /troll it just comes up with a list of commands. When I do any of these commands it just brings up the list again. Also, I saw DoniBobes playing with it, and all he had to do was type the troll such as /sparta instead of /troll sparta so im not sure if I am doing this right. I am pretty sure I have java 8 but 1. I am not sure if you mean I need java 8 for my client or for the server, and 2. I don't know how to check my server java. I have all 3 of the other plugins that some commands need. In Doni's video, when he brought up the list of commands, it was not a big and had multiple pages to go through (/troll help 1, 2, 3 etc) but on my server it just looks like this, and it goes on further than I can scroll up.

https://gyazo.com/0acb55b8d886721b2fba4674854f7d8a

Please help me, I really want to use this plugin.
-66Herobrine66

**Comment by egg82** [comment] 2017-08-28 23:44
No worries!

In the video Doni is using an older version of the plugin. Version 3.x I believe. Due to a huge amount of requests, in 4.x I moved all of the commands into their own subcommands under /troll.
For example, /sparta <player> became /troll sparta <player>

As to why the plugin is just giving you help menus, I can't be sure unless I see what commands you are running and what the output is. I haven't seen any evidence of this behavior on my end.

**Comment by AngelOfCreation** [comment] 2017-08-28 23:47
I did /troll vomit Player420 (my mod) and it just brought up the list. I did a couple other commands but Im not sure which trolls they were. Should I give you my list of plugins? It doesn't show up in console either.

**Comment by AngelOfCreation** [comment] 2017-08-29 00:12
I have to go in a bit. I will be back at about 2:30 EST tomorrow (when I get home).

**Comment by egg82** [comment] 2017-08-29 01:34
/troll vomit egg82 works as expected in version 4.24.47
I had an issue in a previous version where player names with numbers would try to get a list. Have you updated?

**Comment by AngelOfCreation** [comment] 2017-08-29 12:20
Yes I have updated. My username is X66Herobrine66X if thats what you mean. Is there supposed to be a config file generated on first restart? I didn't get anything like that.

(got a break at school)

**Comment by egg82** [comment] 2017-08-29 15:58
No config file. The plugin doesn't touch disk aside from the occasional command that requires NBT (which can be disabled by simply not including an NBT library plugin)

The only thing that comes to mind is that the main command is [successfully parsing an integer from the player name](https://github.com/egg82/TrollCommandsPlusPlus/blob/master/src/me/egg82/tcpp/commands/TrollCommand.java#L118). That shouldn't really happen if the player name is alphanumeric, as evidenced by testing on my moniker "egg82"

However, checking to see if args[0] is a player that exists before attempting to parse a help page from the argument would be a good idea. This is a simple one-line change, but could save some headache.

Edit: using /troll vomit "player" shouldn't spit out /help anyway. [This line](https://github.com/egg82/TrollCommandsPlusPlus/blob/master/src/me/egg82/tcpp/commands/TrollCommand.java#L128) checks the arguments to make sure there's only one argument before proceeding with a fake "/help" command.

**Comment by egg82** [comment] 2017-08-29 16:06
What exactly is the full input and full output of the command you're trying to run? I need to know this to help sole the issue.

**Comment by AngelOfCreation** [comment] 2017-08-29 17:54
Like what happens when I do the command? Well I do /troll vomit <playername> In my case it was Player420 my friend, and it just brings up the list of commands and their descriptions. It doesn't say anything in console but when I get home I can try again to see if something pops up in console. As for the links you put in your message, I honestly have no idea what any of that means. I dont know anything about code so sorry :(. Would you like a list of my plugins? I remember trying other trolls in place of vomit but those did the same thing although I can't remember what trolls I tried.

**Comment by AngelOfCreation** [comment] 2017-08-29 17:56
Ok im about to leave to go home, here is some SS's of my plugins.
https://gyazo.com/89d218272b93e4112903e547b5a85c40
https://gyazo.com/5368b7375fd5e263f10f20c740639fdf
https://gyazo.com/2982ad5e5fccc6025a6bfef71791105c

**Comment by AngelOfCreation** [comment] 2017-08-29 18:32
Ok im home. I have more time now.

**Comment by AngelOfCreation** [comment] 2017-08-29 18:49
Ok I have now tried doing /troll lure X66Herobrine66X and /troll useless X66Herobrine66X again. They both bring up the list of trolls, and nothing shows up in the log.

**Comment by AngelOfCreation** [comment] 2017-08-29 18:50
I have thought of one thing however, I am using the Mo Bends mod and the minecraftcapes mod. Is that an issue? Both are client side only.

**Comment by egg82** [comment] 2017-08-29 21:48
There shouldn't be any issues with client-side mods.

What I mean by full, exact input and output is a screenshot of exactly what you typed in and exactly what you got back. The whole picture, header and all. I need to see exactly what was input and what was returned so I can attempt to re-create it and see where it would have been caught up at.

There are several points in the plugin where commands and descriptions would be output to the player's screen. I need to see if there's a nice-looking header attached to the output and if there's a page (and what page it would be)

**Comment by AngelOfCreation** [comment] 2017-08-30 13:39
Im at school right now, I get home at around 2:30 PM EST. Ill get on my server as soon as I get home and get a couple screenshots. There's no header though, I assume you mean like the one in Doni's video? I will still get screenshots.

**Comment by AngelOfCreation** [comment] 2017-08-30 22:54
What I type:
https://gyazo.com/4c06d6d9919ae68a8ffc103ae90e9e70
What comes up:
https://gyazo.com/935f87fbe118c7afe5a00d1b27027eb5

**Comment by egg82** [comment] 2017-08-31 00:43
I believe another plugin (possibly PlugMan) is taking over the main /troll command. Try temporarily removing all plugins except for TC++ (and recommended libs) from the folder and adding them back one at a time. (You can /reload the server each time you add a new plugin to speed things up)

When you find the conflict, let me know. I'll see what I can do to help resolve the conflict with that plugin author.

The reason I say this is likely a conflict is because nowhere in TC++ does it spit out that information to the player without formatting. Something else is copy/pasting the plugin's internal config file into your chat.

I'll close this for now. Please re-open this if you manage to find the conflict!

**Comment by AngelOfCreation** [comment] 2017-09-01 19:00
That didn't work unfortunately. I took out all plugins except for TC++, PowerNBT, ProtocolLib, and Libs Disguises. It still did the same thing. I then took out all plugins except for TC++ and still it just gave me the same thing. Here are screenshots of my console, in game, and plugins folder. I also tried both doing /reload and restarting from console.

https://gyazo.com/fe9605cd6cbf19b182f6824178494bc5
https://gyazo.com/eb746267fdcacbd64550076a7b84e8f5
https://gyazo.com/dafe214bfece080e492fe1fc699e98c3

Here are 2 screenshots of the first time my server restarted. This was with TC++, PowerNBT, ProtocolLib, and Libs Disguises. I dont know what it means, it might not be important.
https://gyazo.com/3347ae855700cd625c3d345444c77393
https://gyazo.com/ecca0704d9ba3ba65f88baebe498caab

**Comment by egg82** [comment] 2017-09-22 18:13
Re-opening as this still seems to be a problem. I seriously have no idea what's going on, though.

**Comment by egg82** [comment] 2017-09-22 18:26
That last picture you sent: At the bottom it says "Error enabling TrollCommands++" - what does the rest of the error say?

**Comment by TheGlitch76** [comment] 2017-09-23 21:25
Take what i say with a grain of salt, but I've seen LibsDisguises errors like that before and it usually means your using a different version of MC than what the plugin's NMS is using. Then again, that was a while ago. I'll try replicating soon.

**Comment by TheGlitch76** [comment] 2017-09-23 21:29
@X66Herobrine66X, what are your ProtocolLib, LibsDisguises, PowerNBT, TC++, and Bukkit/Spigot versions?

**Comment by AngelOfCreation** [comment] 2017-10-01 20:05
Ok sorry I have been gone I dont check my email very often and I thought you weren't gonna respond. My versions are:
LibsDisguises: 9.1.2
ProtocolLib: 4.2.1
PowerNBT: 0.8.9
TC++: 4.24.48
My server uses 1.12 minecraft not 1.12.2 so that might be the problem. I just restarted my server and it doesn't say "Error enabling TrollCommands++" anymore but the problem is still happening.

**Comment by AngelOfCreation** [comment] 2017-10-09 21:22
Ok im sorry but this plugin just isn't working for me. Thanks for trying to help me with it but I think im just gonna stick with punishmental :/. I wish I could get this to work as it seems much better then punishmental.
Thanks for your time. Sorry.

**Comment by egg82** [comment] 2017-10-10 04:11
For some reason Github has decided it's not going to tell me about thread any more, which is strange. I wasn't actually alerted to any of this conversation until you changed the title.

4.25.49 was released a couple days ago with some bug fixes relating to this issue, but I'm not 100% sure they'll work since I can't reproduce it on my end. I also use 1.12 (compiled three days ago) as my main test server.

However, my plugin versions are different from yours.
LibsDisguises 9.5.0 (or iDisguise 5.6.4)
ProtocolLib 4.3.0
PowerNBT 0.8.9.2 (or Item-NBT-API 1.5.1)
TC++ 4.25.49

though I don't see how any of this would affect your issue, you should probably update them anyway. I've also been waiting for my error reporting service to roll over so I can capture new errors that might've shown themselves between now and then. If you've encountered that issue in the last couple days and it's actually thrown an internal error somewhere I'll have seen it and I'm working on a bugfix/Bungeecord update that will be out in the next few days.

Otherwise, yeah, I'll mark this as closed for now.

**Closed as completed by egg82** 2017-10-10 04:11 UTC
